Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/university.eu/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.university.eu/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.university.eu:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  Capabilities:
    <<: *OrdererCapabilities
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('OrdererMSP.admin')"
    BlockValidation:
      Type: Signature
      Rule: "OR('OrdererMSP.member')"
  EtcdRaft:
    Consenters:
      - Host: orderer.university.eu
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/university.eu/orderers/orderer.university.eu/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/university.eu/orderers/orderer.university.eu/tls/server.crt
    Options:
      TickInterval: 500ms
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 20 MB

Application: &ApplicationDefaults
  Organizations:
    - *Org1
  Capabilities:
    <<: *ApplicationCapabilities
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin')"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin', 'OrdererMSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.client', 'Org1MSP.peer', 'Org1MSP.admin', 'OrdererMSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'OrdererMSP.admin')"
    Endorsement:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org1MSP.admin', 'OrdererMSP.member')"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1

  RegistrationAppChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
