OrdererOrgs:
  - Name: Orderer
    Domain: university.eu
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.university.eu
    Template:
      Count: 2
    Users:
      Count: 1
