volumes:
  orderer.university.eu:
  peer0.org1.university.eu:
  peer1.org1.university.eu:
  ca.org1.university.eu:
  couchdb0.org1.university.eu:
  couchdb1.org1.university.eu:

services:
  cli:
    image: hyperledger/fabric-tools:latest
    container_name: cli
    environment:
      - CORE_PEER_ADDRESS=peer0.org1.university.eu:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/org1.university.eu/peers/peer0.org1.university.eu/tls/ca.crt
    volumes:
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./crypto-config/peerOrganizations/org1.university.eu/users/Admin@org1.university.eu/msp:/etc/hyperledger/fabric/msp
      - ./scripts:/etc/hyperledger/fabric/scripts
      - ./chaincodes:/etc/hyperledger/fabric/chaincodes
    command: bash -c "/etc/hyperledger/fabric/scripts/channel-setup.sh"
    depends_on:
      - orderer.university.eu
      - peer0.org1.university.eu
      - peer1.org1.university.eu
    networks:
      - university_network
  ca.org1.university.eu:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.university.eu
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca-server-config:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.university.eu
    networks:
      - university_network

  orderer.university.eu:
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      # - ORDERER_GENERAL_GENESISMETHOD=file
      # - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/university.eu/orderers/orderer.university.eu/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/university.eu/orderers/orderer.university.eu/tls:/var/hyperledger/orderer/tls
      - orderer.university.eu:/var/hyperledger/production/orderer
    expose:
      - 7050
    container_name: orderer.university.eu
    hostname: orderer.university.eu
    networks:
      - university_network

  peer0.org1.university.eu:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=university_network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.university.eu:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.university.eu:7051
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.org1.university.eu
      - CORE_PEER_ADDRESS=peer0.org1.university.eu:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.university.eu:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1.university.eu:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couch
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpw
    volumes:
      - ./crypto-config/peerOrganizations/org1.university.eu/peers/peer0.org1.university.eu/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.university.eu/peers/peer0.org1.university.eu/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - /var/run/docker.sock:/var/run/docker.sock
      - peer0.org1.university.eu:/var/hyperledger/production
    expose:
      - 7051
      - 7052
    container_name: peer0.org1.university.eu
    hostname: peer0.org1.university.eu
    depends_on:
      - couchdb0.org1.university.eu
    networks:
      - university_network

  couchdb0.org1.university.eu:
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=couch
      - COUCHDB_PASSWORD=couchpw
      - COUCHDB_BIND_ADDRESS=0.0.0.0
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_TLS=enable
      - COUCHDB_TLS_CERT_FILE=/opt/couchdb/cert/couch0.crt
      - COUCHDB_TLS_KEY_FILE=/opt/couchdb/cert/couch0.key
      - COUCHDB_TLS_CA_FILE=/opt/couchdb/cert/ca.university.eu-cert.pem
    ports:
      - "5984:5984"
      - "6984:5984"
    volumes:
      - couchdb0.org1.university.eu:/opt/couchdb/data
      - ./certs:/opt/couchdb/cert
    container_name: couchdb0.org1.university.eu
    hostname: couchdb0.org1.university.eu
    networks:
      - university_network

  peer1.org1.university.eu:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=university_network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.university.eu:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.university.eu:8051
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer1.org1.university.eu
      - CORE_PEER_ADDRESS=peer1.org1.university.eu:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.university.eu:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.org1.university.eu:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couch
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpw
    volumes:
      - ./crypto-config/peerOrganizations/org1.university.eu/peers/peer1.org1.university.eu/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.university.eu/peers/peer1.org1.university.eu/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - /var/run/docker.sock:/var/run/docker.sock
      - peer1.org1.university.eu:/var/hyperledger/production
    expose:
      - 8051
      - 8052
    container_name: peer1.org1.university.eu
    hostname: peer1.org1.university.eu
    depends_on:
      - couchdb1.org1.university.eu
      - peer0.org1.university.eu
    networks:
      - university_network

  couchdb1.org1.university.eu:
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=couch
      - COUCHDB_PASSWORD=couchpw
      - COUCHDB_BIND_ADDRESS=0.0.0.0
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_TLS=enable
      - COUCHDB_TLS_CERT_FILE=/opt/couchdb/cert/couch1.crt
      - COUCHDB_TLS_KEY_FILE=/opt/couchdb/cert/couch1.key
      - COUCHDB_TLS_CA_FILE=/opt/couchdb/cert/ca.university.eu-cert.pem
    ports:
      - "5985:5984"
      - "6985:5984"
    volumes:
      - couchdb1.org1.university.eu:/opt/couchdb/data
      - ./certs:/opt/couchdb/cert
    container_name: couchdb1.org1.university.eu
    hostname: couchdb1.org1.university.eu
    networks:
      - university_network
  
  django:
    image: python:3.11
    container_name: django_app
    environment:
      - GRPC_DNS_RESOLVER=ipv4
    volumes: 
      - ./university_management:/app
      - ./certs:/app/certs
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
               python manage.py runserver_plus 0.0.0.0:8000 --cert-file /app/certs/django.crt --key-file /app/certs/django.key" 
    ports:
      - "8000:8000"
    depends_on:
      - orderer.university.eu
      - peer0.org1.university.eu
      - peer1.org1.university.eu
    networks:
      - university_network

networks:
  university_network:
    name: university_network
    driver: bridge
