NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org1.university.eu-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org1.university.eu-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.org1.university.eu-cert.pem
    OrganizationalUnitIdentifier: admin_org1
  OrdererOUIdentifier:
    Certificate: cacerts/ca.org1.university.eu-cert.pem
    OrganizationalUnitIdentifier: orderer
