version: 1.0.0
ca:
  name: ca.org1.university.eu
  keyfile: ./priv_sk
  certfile: ./ca.org1.university.eu-cert.pem
  tls:
    enabled: true
    certfile: ./ca.org1.university.eu-cert.pem
    keyfile: ./priv_sk
  affiliations:
    org1:
      - peer
      - admin
      - client
      - orderer
  maxEnrollments: -1
registry:
  identities:
    - name: admin
      pass: adminpw
      type: admin
    - name: user
      pass: userpw
      type: client
    - name: django
      pass: djangopw
      type: client
    - name: couch0
      pass: couch0pw
      type: client
    - name: couch1
      pass: couch1pw
      type: client
