# Generated by Django 5.1.2 on 2024-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentactivitygrade',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='title',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
